apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventportal-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventportal-backend
  template:
    metadata:
      labels:
        app: eventportal-backend
    spec:
      containers:
      - name: backend
        image: shashihere/eventportal-backend:v1
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: eventportal-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventportal-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventportal-frontend
  template:
    metadata:
      labels:
        app: eventportal-frontend
    spec:
      containers:
      - name: frontend
        image: shashihere/eventportal-frontend:v1
        ports:
        - containerPort: 80
